# Generated by Django 4.2.4 on 2023-08-07 11:58

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_like_like_num'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('search_object', django.db.models.manager.Manager()),
            ],
        ),
    ]
