# Generated by Django 4.2.4 on 2023-08-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(default='null', max_length=512),
            preserve_default=False,
        ),
    ]
